package com.piratesgaming.unsolved;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public class UnsolvedCommand implements CommandExecutor,TabCompleter{
 private final PiratesUnsolved p; public UnsolvedCommand(PiratesUnsolved p){this.p=p;}
 private boolean admin(CommandSender s){if(s.isOp()||s.hasPermission("unsolved.admin"))return true;s.sendMessage(ChatColor.RED+"You don't have permission: unsolved.admin");return false;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(a.length==0){s.sendMessage(ChatColor.GOLD+"/us help");return true;}String x=a[0].toLowerCase();
  if(x.equals("help")){s.sendMessage(ChatColor.GOLD+"=== Unsolved SMP Commands ===");s.sendMessage("/us start / stop / reload / spin <player>");s.sendMessage("/us eliminate <player> / revive <player>");s.sendMessage("/us killsrank <on|off> / us loginsecurity <on|off>");s.sendMessage("/us ipsecurity <on|off> / us sameip <add|remove|list> <player>");s.sendMessage("/us whitelist <on|off|add|remove|list> [player]");s.sendMessage("/us banitem <add|remove|list> <craft|pickup|inventory|drop|place|all> [material]");s.sendMessage("/us mace <on|off> /us syncgroups");return true;}
  if(x.equals("start")){if(!admin(s))return true;p.getConfig().set("season-started",true);p.saveConfig();for(Player q:Bukkit.getOnlinePlayers())p.spin(q);Bukkit.broadcastMessage(ChatColor.GOLD+"Unsolved SMP Season 1 has started!");return true;}
  if(x.equals("stop")){if(!admin(s))return true;p.getConfig().set("season-started",false);p.saveConfig();Bukkit.broadcastMessage(ChatColor.RED+"Unsolved SMP Season 1 has stopped.");return true;}
  if(x.equals("reload")){if(!admin(s))return true;p.reloadPlugin();s.sendMessage(ChatColor.GREEN+"Unsolved SMP reloaded.");return true;}
  if(x.equals("spin")){if(!admin(s)||a.length<2)return true;Player q=Bukkit.getPlayerExact(a[1]);if(q!=null)p.spin(q);return true;}
  if(x.equals("syncgroups")){if(!admin(s))return true;p.syncRankOrder();s.sendMessage(ChatColor.GREEN+"LuckPerms groups synced automatically.");return true;}
  if(x.equals("killsrank")||x.equals("loginsecurity")||x.equals("ipsecurity")||x.equals("mace")||x.equals("trialchambers")||x.equals("anticheat")){if(!admin(s)||a.length<2)return true;String key=switch(x){case"killsrank"->"kills-rank";case"loginsecurity"->"login-security";case"ipsecurity"->"ip-security";case"mace"->"mace";case"trialchambers"->"trial-chambers";default->"anticheat";};boolean v=a[1].equalsIgnoreCase("on")||a[1].equalsIgnoreCase("true");p.getConfig().set(key,v);p.saveConfig();s.sendMessage(ChatColor.GREEN+x+" = "+v);return true;}
  if(x.equals("sameip")){if(!admin(s))return true;if(a.length<2)return true;String op=a[1].toLowerCase();List<String> w=p.getConfig().getStringList("sameip-whitelist");if(op.equals("list")){s.sendMessage(ChatColor.YELLOW+"Same-IP whitelist: "+String.join(", ",w));return true;}if(a.length<3)return true;w.removeIf(z->z.equalsIgnoreCase(a[2]));if(op.equals("add")){w.add(a[2]);Player target=Bukkit.getPlayerExact(a[2]);if(target!=null&&target.getAddress()!=null){List<String> ips=p.getConfig().getStringList("sameip-ips");String h=p.ipHash(target.getAddress().getAddress().getHostAddress());if(!ips.contains(h))ips.add(h);p.getConfig().set("sameip-ips",ips);}}p.getConfig().set("sameip-whitelist",w);p.saveConfig();s.sendMessage(ChatColor.GREEN+"Same-IP whitelist updated.");return true;}
  if(x.equals("whitelist")){if(!admin(s))return true;if(a.length<2)return true;String op=a[1].toLowerCase();if(op.equals("on")||op.equals("off")){p.getConfig().set("whitelist",op.equals("on"));p.saveConfig();s.sendMessage(ChatColor.GREEN+"Whitelist "+op+".");return true;}List<String>w=p.getConfig().getStringList("whitelist-players");if(op.equals("list")){s.sendMessage(ChatColor.YELLOW+"Whitelist: "+String.join(", ",w));return true;}if(a.length<3)return true;w.removeIf(z->z.equalsIgnoreCase(a[2]));if(op.equals("add"))w.add(a[2]);p.getConfig().set("whitelist-players",w);p.saveConfig();s.sendMessage(ChatColor.GREEN+"Whitelist updated.");return true;}
  if(x.equals("eliminate")||x.equals("revive")){if(!admin(s)||a.length<2)return true;Player q=Bukkit.getPlayerExact(a[1]);UUID id=Bukkit.getOfflinePlayer(a[1]).getUniqueId();if(x.equals("eliminate")){p.getConfig().set("eliminated."+id,true);p.saveConfig();if(q!=null){q.sendMessage(ChatColor.RED+"You have been eliminated from Unsolved SMP Season 1.");q.kickPlayer("You have been eliminated from Unsolved SMP Season 1.");}Bukkit.broadcastMessage(ChatColor.RED+a[1]+" has been eliminated from Unsolved SMP Season 1.");}else{p.getConfig().set("eliminated."+id,false);p.saveConfig();if(q!=null){q.sendMessage(ChatColor.GREEN+"You have been revived in Unsolved SMP Season 1.");}Bukkit.broadcastMessage(ChatColor.GREEN+a[1]+" has been revived in Unsolved SMP Season 1.");}return true;}
  if(x.equals("banitem")){if(!admin(s)||a.length<2)return true;String op=a[1].toLowerCase();if(op.equals("list")){s.sendMessage(ChatColor.YELLOW+"Ban-item settings saved in config.yml");return true;}if(a.length<4)return true;String mode=a[2].toLowerCase(),mat=a[3].toUpperCase();try{Material.valueOf(mat);}catch(Exception e){s.sendMessage(ChatColor.RED+"Invalid Minecraft material.");return true;}p.getConfig().set("ban-items."+mode+"."+mat,op.equals("add"));p.saveConfig();s.sendMessage(ChatColor.GREEN+"Banitem "+op+": "+mat+" for "+mode);return true;}
  s.sendMessage(ChatColor.RED+"Unknown command. Use /us help");return true; }
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length==1)return Arrays.asList("help","start","stop","reload","spin","eliminate","revive","killsrank","loginsecurity","ipsecurity","sameip","whitelist","banitem","mace","trialchambers","anticheat","syncgroups");if(a.length==2){if(Set.of("killsrank","loginsecurity","ipsecurity","mace","trialchambers","anticheat").contains(a[0].toLowerCase()))return List.of("on","off");if(a[0].equalsIgnoreCase("sameip"))return List.of("add","remove","list");if(a[0].equalsIgnoreCase("whitelist"))return List.of("on","off","add","remove","list");if(a[0].equalsIgnoreCase("banitem"))return List.of("add","remove","list");if(Set.of("spin","eliminate","revive").contains(a[0].toLowerCase()))return Bukkit.getOnlinePlayers().stream().map(Player::getName).toList();}if(a.length==3&&a[0].equalsIgnoreCase("banitem")&&(a[1].equalsIgnoreCase("add")||a[1].equalsIgnoreCase("remove")))return List.of("craft","pickup","inventory","drop","place","all");if(a.length==4&&a[0].equalsIgnoreCase("banitem")){try{return Arrays.stream(org.bukkit.Material.values()).map(Enum::name).toList();}catch(Exception ignored){}}return Collections.emptyList();}
}
